[package]
name = "hermit-sys"
version = "0.1.8"
authors = ["Stefan Lankes"]
license = "MIT/Apache-2.0"
description = "FFI bindings to HermitCore"
repository = "https://github.com/hermitcore/rusty-hermit"
readme = "README.md"
keywords = ["unikernel", "libos"]
categories = ["os"]
links = "hermit"
build = "build.rs"

[dependencies]
log = { version = "0.4", default-features = false }
lazy_static = "1.4.0"

[target.'cfg(target_arch = "x86_64")'.dependencies.x86]
version = "0.*"
default-features = false

[dependencies.smoltcp]
version = "0.6.0"
optional = true
default-features = false
features = ["log", "verbose", "std", "ethernet", "socket-udp", "socket-tcp", "proto-ipv4", "proto-ipv6"]
